import "./globals.css";
import { Inter } from 'next/font/google';

// フォント情報の設定
const inter = Inter({ subsets: ["latin"] })

// メタ情報の準備
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ルートレイアウトの準備
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
